services:
  - type: web
    name: student-performance-predictor-api
    env: python
    region: oregon
    plan: free
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: >
      python -m uvicorn backend.main:app
      --host 0.0.0.0
      --port $PORT
    envVars:
      - key: PYTHONIOENCODING
        value: utf-8
      - key: PYTHONPATH
        value: .
